CC = gcc
LD = gcc

# The name of the final executable
TARGET = cfans

# Directories
SRC_DIR = src
EXT_DIR = external
OBJ_DIR = obj
BIN_DIR = bin

# Source files
# Find all .c files in SRC_DIR and add the inih.c from the submodule
SRCS = $(wildcard $(SRC_DIR)/*.c) $(EXT_DIR)/inih/ini.c

# Object files
# Generate object file names in OBJ_DIR, corresponding to each source file
OBJS = $(addprefix $(OBJ_DIR)/, $(notdir $(SRCS:.c=.o)))

# Dependency files generated by the compiler
DEPS = $(OBJS:.o=.d)

# pkg-config packages
PKGS = libsystemd

# Compiler, preprocessor, and linker flags
# Use CFLAGS for compiler-specific flags (warnings, optimization)
# Use CPPFLAGS for preprocessor-specific flags (includes, defines)
# Use LDFLAGS for linker-specific flags
# Use LDLIBS for libraries to link
CFLAGS = -Wall -Wextra
CPPFLAGS = -MMD -MP -I$(EXT_DIR)/inih -DINI_CALL_HANDLER_ON_NEW_SECTION=1 -DINI_STOP_ON_FIRST_ERROR=1
LDFLAGS =
LDLIBS = $(shell pkgconf --libs $(PKGS))

# Add debug symbols if DEBUG=1 is passed to make
ifeq ($(DEBUG), 1)
	CFLAGS += -g
endif

# VPATH tells make where to find source files
VPATH = $(SRC_DIR) $(EXT_DIR)/inih

# The final executable path
TARGET_BIN = $(BIN_DIR)/$(TARGET)

.PHONY: all clean

all: $(TARGET_BIN)

# Rule to link the final executable
$(TARGET_BIN): $(OBJS)
	@mkdir -p $(@D)
	$(LD) $(LDFLAGS) $^ -o $@ $(LDLIBS)

# Generic rule to compile any .c file into an object file in OBJ_DIR
# It finds the source file using VPATH
$(OBJ_DIR)/%.o: %.c
	@mkdir -p $(@D)
	$(CC) $(CPPFLAGS) $(CFLAGS) -c $< -o $@

clean:
	@echo "Cleaning up object and binary files..."
	rm -rf $(OBJ_DIR) $(BIN_DIR)

# Include all dependency files
-include $(DEPS)
